name: Six WF
on: push
jobs:
  six-job:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Check maven version
        id: maven_version
        run: mv -v
      - name: Check maven version
        if: failure() && steps.maven_version.outcome == 'failure'
        run: npm -v
  other-job:
    needs: six-job
    name: Run after second-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
    
  
      
        
