name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print Bye
        run: echo "Bye"
      - name: Multi line cmd
        run: |
          echo "Hello"
          echo "Bye"
